version: "3"
services:
  mysql:
    image: mysql:8.0.33

    container_name: colecto-mysql
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_DATABASE: colecto
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: 1234
    ports:
      - 9595:3306

    volumes:
      - colecto:/mysql

  redis:
    container_name: colecto-redis

    image: redis
    ports:
      - 9596:6379

    volumes:
      - colecto:/redis

  springbootapp:
    build: .
    container_name: springbootapp

    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis

volumes:
  colecto:
